baseurl = "/"
title = "Hugo Website"
theme = "hugo-theme-nix"
languageCode = "en-us"
disqusShortname = "your_disqus_shortname"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
  GithubID = "masterswords98"
  LinkedInID = "neel-homchowdhury-42807b178/"
  InstagramID = "kneelb4neel"
  Name = "Neel Homchowdhury"
  HeaderUsername = "neel"
  HeaderHostname = "gohugo.io"
  Email = "neelhom@gmail.com"
  About = "Hi I'm Neel! I am a Data Scientist/Data Analyst interested in applying mathematical and statistical models in order to study the impacts of consumer behavior, social psychology, and artist popularity within the music industry. This website contains some of my past and ongoing projects. If you'd like to learn more about me, feel free to check out the 'about' tab. Enjoy!"
  ProfilePicture = "https://lh3.googleusercontent.com/yxfhtbmg8LfmhJJCE2y8UB4oHNTgQ9Tf9M5eVeLJsAfmvcddZ0YAugnqzsCaYrlbnYkZhVHcsL4IGIdloXxEjsc6iXS-u1tsfPQxVFjNIxuOCRgRgDdAU9FL2xUghfAnulFJNmgXeA=w2400"
  Favicon = "/favicon.ico"

